gems:
  - jekyll-paginate

markdown:         kramdown
highlighter:      rouge

# Site settings
title: Lisp Game Jams

description: "Lisp-themed events by #lispgames community"

paginate_path: "/blog/page:num/"
paginate: 5
