# Gems
gems:
  - jekyll-paginate

# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            Lisp Game Jams
tagline:          '#lispgames community-driven events'
description:      'Lisp-themed game jams by #lispgames community'
url:              http://lispgamejam.org
baseurl:          /lispgamejam.org/

author:
  name:           'Mark Otto'
  url:            https://twitter.com/mdo

paginate_path:    /lispgamejam.org/blog/page:num/
paginate:         5

# Custom vars
lispgames:
  website:        http://lispgames.org
